version: "3.8"

services:
  web:
    build:
      context: .
      args:
        TAG: jp17
    container_name: jobportal-app-container
    image: brijesh35/my-jobportal-app:jp17
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
