version: "3.8"

services:
  web:
    build: .
    container_name: jobportal-app-container
    image: ${{ secrets.DOCKER_USERNAME }}/my-jobportal-app:${{ github.run_number }}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000