name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker-compose build --build-arg TAG=brijesh35/my-jobportal-app:${{ github.run_number }}
        docker images # Add this line for debugging
        echo "::set-env name=DOCKER_IMAGE_TAG::${GITHUB_RUN_NUMBER}"

    - name: Deploy to Kubernetes
      uses: appleboy/kubernetes-action@master
      with:
          k8s_manifest: ./path/to/deployment.yaml
          image: brijesh35/my-jobportal-app:${{ env.DOCKER_IMAGE_TAG }}

    - name: Push Docker image to Docker Hub
      run: |
        docker-compose push
        echo "Docker image pushed successfully"
